[build]
  command = "npm install && npm run build"
  publish = "dist"
  port = 10000
  targetPort = 10000
  functions = "netlify/functions"
[build.environment]
  NODE_VERSION = "18.x"

[[redirects]]
  from = "/api/*"
  to = "https://pdf-table-processor.onrender.com/:splat"  # Backend'e yönlendirme
  status = 200
  force = true
  # Proxy için gerekli header'ları ekleyin
  [redirects.headers]
    Access-Control-Allow-Origin = "https://pdftableprocessor.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/*"
  [headers.values]
    # Sadece frontend için CORS ayarları
    Access-Control-Allow-Origin = "https://pdftableprocessor.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
